services:
  - type: web
    name: n8n
    env: docker
    region: singapore
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: N8N_HOST
        value: nishant-chro.app.n8n.cloud
      - key: N8N_PROTOCOL
        value: https
      - key: WEBHOOK_URL
        value: https://nishant-chro.app.n8n.cloud
      - key: TZ
        value: Asia/Kolkata
      - key: N8N_ENCRYPTION_KEY
        generateValue: true
